export const profileMapping = {
  docente: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
    { key: "nombres", label: "Nombres" },
    { key: "primer_apellido", label: "Primer Apellido" },
    { key: "segundo_apellido", label: "Segundo Apellido" },
    { key: "correo_electronico", label: "Email" },
    { key: "numero_contacto_1", label: "Teléfono" },
    { key: "numero_contacto_2", label: "Teléfono Alternativo" },
    { key: "estado_inscripcion", label: "Estado Inscripción" },
    { key: "validacion", label: "Estado Validación" },
    { key: "rinde_pf", label: "Rinde / No Rinde" },
    { key: "debe_rendir", label: "Debe Rendir" },
    { key: "agrupacion", label: "Agrupacion" },
    { key: "asignatura", label: "Asignatura" },
    { key: "estado_grab_raptor", label: "Grabación (Raptor)" },
    { key: "estado_grab_dmas", label: "Grabación (D+)" },
    { key: "rbd", label: "RBD" },
    { key: "nombre_establecimiento", label: "Nombre Establecimiento" },
    { key: "dependencia", label: "Dependencia" },
    { key: "rut_sostenedor", label: "RUT Sostenedor" },
    { key: "nombre_sostenedor", label: "Nombre Sostenedor" },
    { key: "a19ñ", label: "Beneficio: 19Ñ" },
    { key: "avolun", label: "Beneficio: Tramo Voluntario" },
    { key: "uaplaza", label: "Beneficio: Aplazamiento Proceso Evaluativo" },
    
    { key: "estado_susp", label: "Estado Solicitud Suspensión" },
  ],
  //SOSTENEDOR
  representante: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
    { key: "nombres", label: "Nombres" },
    { key: "primer_apellido", label: "Primer Apellido" },
    { key: "segundo_apellido", label: "Segundo Apellido" },
    { key: "correo_electronico", label: "Email" },
    { key: "numero_contacto_1", label: "Teléfono" },
    { key: "estrategico", label: "Estratégico" },
    { key: "rbd", label: "RBD" },
    { key: "nombre_establecimiento", label: "Nombre Establecimiento" },
    { key: "dependencia", label: "Dependencia" },
    { key: "rut_sostenedor", label: "RUT Sostenedor" },
    { key: "nombre_sostenedor", label: "Nombre Sostenedor" },
    { key: "ultimo_ingreso", label: "Último acceso" },
  ],
  director: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
    { key: "nombres", label: "Nombres" },
    { key: "primer_apellido", label: "Primer Apellido" },
    { key: "segundo_apellido", label: "Segundo Apellido" },
    { key: "correo_electronico", label: "Email" },
    { key: "numero_contacto_1", label: "Teléfono" },
    { key: "rbd", label: "RBD" },
    { key: "nombre_establecimiento", label: "Nombre Establecimiento" },
    { key: "dependencia", label: "Dependencia" },
    { key: "rut_sostenedor", label: "RUT Sostenedor" },
    { key: "nombre_sostenedor", label: "Nombre Sostenedor" },
    { key: "ultimo_ingreso", label: "Último acceso" },
  ],
  coordinador_grabacion: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
    { key: "nombres", label: "Nombres" },
    { key: "primer_apellido", label: "Primer Apellido" },
    { key: "segundo_apellido", label: "Segundo Apellido" },
    { key: "correo_electronico", label: "Email" },
    { key: "numero_contacto_1", label: "Teléfono" },
    { key: "rbd", label: "RBD" },
    { key: "nombre_establecimiento", label: "Nombre Establecimiento" },
    { key: "dependencia", label: "Dependencia" },
    { key: "rut_sostenedor", label: "RUT Sostenedor" },
    { key: "nombre_sostenedor", label: "Nombre Sostenedor" },
    { key: "ultimo_ingreso", label: "Último acceso" },
  ],
  encargado: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
    { key: "nombres", label: "Nombres" },
    { key: "primer_apellido", label: "Primer Apellido" },
    { key: "segundo_apellido", label: "Segundo Apellido" },
    { key: "correo_electronico", label: "Email" },
    { key: "numero_contacto_1", label: "Teléfono" },
    { key: "estrategico", label: "Estratégico" },
    { key: "rbd", label: "RBD" },
    { key: "nombre_establecimiento", label: "Nombre Establecimiento" },
    { key: "dependencia", label: "Dependencia" },
    { key: "rut_sostenedor", label: "RUT Sostenedor" },
    { key: "nombre_sostenedor", label: "Nombre Sostenedor" },
    { key: "ultimo_ingreso", label: "Último acceso" },
  ],
  no_identificado: [
    { key: "rut", label: "RUT" },
    { key: "dv", label: "Dígito Verificador" },
  ],
};
